### ISSUE TITLE
There is no way to specify Docker registry

### ISSUE THREAD

**Issue by uladzimir-shelhunou** [nikcub/containr#1]
Hi @nikcub,

I did not find the way to specify registry url, is there any?

Thanks,
Uladzimir

**Comment by nikcub** [comment]
Hey @vvsh - i'll fix that in the next release, should be up in a couple of days.

**Comment by uladzimir-shelhunou** [comment]
@nikcub, thank you!

**Comment by nikcub** [comment]
just added support with a new release, define your docker image host in package.json using the repositories key:

```json
"repositories": [
    {
      "type": "docker",
      "url": "hub-on.azurecr.io",
      "path": "api-server"
    }
  ],
```

**Comment by uladzimir-shelhunou** [comment]
@nickub, thank you!
